Repository rolling-paper-toy/front-end, pull requests merged in 2024-11, with the labels that each got.

#28 [feature] MUI 컴포넌트 사용하여 홈페이지에 적용
  src/components/MuiButton.js
  src/components/MuiColor.js
  src/components/SocialLogin.js
Labels: ✨ feature, 🎨 markup, 🎯 ui/ux

#29 Feature/token fetch update
  src/pages/MyPage.js
  src/pages/RedirectHandler.js
Labels: ✨ feature, 🔨 refactor, 🔗 api

#31 [Feature] mypage 내 롤 생성 기능 구현
  src.zip
  src/App.js
  src/components/SocialLogin.js
  src/pages/MyPage.js
Labels: ✨ feature

#35 [Fix] 로그인 페이지에서 소셜 로그인 버튼 수정 및 ux/ui 수정
  public/images/socialLoginButtons/naverSocialLogin.png
  src/components/MuiButton.js
  src/components/SocialLogin.js
  src/pages/LoginPage.js
  src/styles/common/App.css
  src/styles/components/SocialLogin.css
  src/styles/pages/LoginPage.css
Labels: 🎨 markup, 🎯 ui/ux

#34 [Fix] 롤 수정 삭제 api 토큰 인증 및 롤 수정 삭제 시 브라우저 새로고침하여 결과 반영 구현
  src/components/RollItem.js
Labels: 🔗 api, 🐛 bugfix

#37 [REFACTOR] mypage 에서 학급 삭제 시 팝업창에 취소 버튼 추가 및 전반적인 디자인 수정
  package-lock.json
  package.json
  src/components/MuiButton.js
  src/components/MuiColor.js
  src/components/MuiIcon.js
  src/components/RollItem.js
  src/pages/MyPage.js
  src/styles/pages/MyPage.css
Labels: 🔨 refactor, 🎯 ui/ux

#41 [Feature] roll 에서 수정 Click 시 수정 Modal 화면 노출
  src/components/RollItem.js
  src/components/UpdateRollModal.js
  src/styles/components/Modal.css
Labels: ✨ feature, 🔨 refactor, 🎨 markup, 🎯 ui/ux

#46 [main] Paper 각각의 롤링페이퍼 하트모양으로 수정 및 롤링페이퍼에 있는 Modal 내 내용 및 버튼 CSS 수정
  src/components/CreatePaperModal.js
  src/components/PaperDetailModal.js
  src/components/PaperItem.js
  src/pages/RollingPaperPage.js
  src/styles/components/Modal.css
  src/styles/pages/RollingPaperPage.css
Labels: 🎨 markup, 🎯 ui/ux

#49 [main] 학생 로그인 화면 라벨 추가 및 입력칸 너비 조정
  src/components/StudentSignin.js
  src/styles/components/StudentSignin.css
Labels: 🎨 markup, 🎯 ui/ux

#56 [REFACTOR] 전체 기능 테스트 후 학생 로그인 시 입력값 제약 적용 및 Enter 키에 롤 수정 함수 작동 기능 부여
  src/App.js
  src/components/SocialLogin.js
  src/components/StudentSignin.js
  src/components/UpdateRollModal.js
  src/pages/LoginPage.js
Labels: ✅ test, 🔨 refactor, 🔗 api, 🐛 bugfix

#61 [REFACTOR] 배포 환경에 맞춰 API 엔드포인트 도메인 변경
  src/components/CreatePaperModal.js
  src/components/CreateRollModal.js
  src/components/PaperDetailModal.js
  src/components/RollItem.js
  src/components/StudentSignin.js
  src/components/UpdateRollModal.js
Labels: 🔗 api, 🛠️ config

#64 [FEATURE] 플랫폼 별로 파비콘 설정
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  public/index.html
Labels: ✨ feature, 🎨 markup, 🎯 ui/ux

#70 [Fix] 롤링페이퍼 페이지에서 From. {이름}이 두 번 노출되는 현상 수정
  src/components/PaperItem.js
Labels: 🎨 markup, 🎯 ui/ux

#72 [Fix] From.{이름} 두번 나오는 현상 수정중
  src/components/PaperItem.js
Labels: 🎨 markup, 🐛 bugfix, 🎯 ui/ux

#74 refactor : method가 GET이라면 navigate 이동 조건 추가
  src/pages/RollingPaperPage.js
Labels: 🔨 refactor

#79 [ui/ux] 학생일 경우 타 사용자 페이퍼 열람 시 하단 여백 추가
  src/components/PaperDetailModal.js
Labels: 🎯 ui/ux

#84 [REFACTOR] mypage CSS 수정
  src/components/RollItem.js
  src/pages/MyPage.js
  src/styles/pages/MyPage.css
Labels: 🎯 ui/ux

#85 [REFACTOR] 갤럭시탭 S5e 환경에서 마이페이지 내 가이드 말풍선 위치 수정
  src/pages/MyPageDev.js
  src/styles/pages/MyPage.css
Labels: 🎯 ui/ux

#87 [Refactor] 롤링페이퍼 detail modal 'X' 버튼 생성 및 CSS 수정
  src/App.js
  src/components/PaperDetailModal.js
  src/styles/components/Modal.css
  src/styles/pages/RollingPaperPage.css
Labels: 🔨 refactor, 🎨 markup, 🎯 ui/ux

#92 [Refactor] 학생 로그인 페이지에 비밀번호 입력 시 문자가 아닌 숫자만 입력할 수 있도록 유도
  src/components/StudentSignin.js
  src/components/StudentSigninDev.js
  src/styles/components/StudentSignin.css
Labels: 🔨 refactor, 🐛 bugfix, 🎯 ui/ux

#93 [Refactor] 각각의 롤링페이퍼 배경색을 랜덤으로 설정
  src/components/PaperItem.js
Labels: ✨ feature, 🔨 refactor, 🎨 markup, 🎯 ui/ux
