Repository rolling-paper-toy/front-end, pull requests merged in 2024-10, with the labels that each got.

#6 Feature/UI 기능 구현
  .gitignore
  db/initdb.d/1-schema.sql
  db/initdb.d/my.cnf
  docker-compose.yml
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/images/logo/rollingPaperLogo.webp
  public/images/socialLoginButtons/kakaoSocialLogin.png
  public/images/socialLoginButtons/naverSocialLogin.png
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/app/store.js
  src/components/CreatePaperModal.js
  src/components/EditPaperModal.js
  src/components/RollingPaperDetail.js
  src/components/RollingPaperItem.js
  src/components/SocialLogin.js
  src/components/StudentSignin.js
  src/features/students/studentActions.js
  src/features/students/studentSlice.js
  src/input.css
  src/output.css
  src/pages/LoginPage.js
  src/pages/MyPage.js
  src/pages/RollingPaperPage.js
  src/pages/StudentSigninPage.js
  src/services/authService.js
  src/styles/common/App.css
  src/styles/common/Logo.css
  src/styles/components/Header.css
  src/styles/components/PaperModal.css
  src/styles/components/RollingPaperDetail.css
  src/styles/components/SocialLogin.css
  src/styles/components/StudentSignin.css
  src/styles/pages/LoginPage.css
  src/styles/pages/MyPage.css
  src/styles/pages/RollingPaperPage.css
  tailwind.config.js
Labels: ✨ feature, 🎨 markup

#9 Feature/My Page 내 롤 제목 수정 기능 구현
  src.zip
  src/App.js
  src/components/CreatePaperModal.js
  src/components/PaperDetailModal.js
  src/components/Roll.js
  src/components/RollingPaperDetail.js
  src/components/StudentSignin.js
  src/pages/MyPage.js
  src/pages/RollingPaperPage.js
  src/pages/StudentSigninPage.js
  src/styles/pages/MyPage.css
Labels: ✨ feature

#11 [Feature] 모바일 화면 수정
  .idea/workspace.xml
  src/styles/common/App.css
Labels: 🎨 markup, 🎯 ui/ux

#17 Feature/카카오 social login 실행 시 인증 서버로 이동 요청 설정
  .gitignore
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/rolling-paper-frontend.iml
  .idea/vcs.xml
  .idea/workspace.xml
  db/initdb.d/1-schema.sql
  db/initdb.d/my.cnf
  docker-compose.yml
  src.zip
  src/App.js
  src/components/Roll.js
  src/components/RollingPaperDetail.js
  src/components/RollingPaperItem.js
  src/components/SocialLogin.js
  src/pages/KakaoRedirectHandler.js
  src/pages/MyPage.js
  src/pages/NaverRedirectHandler.js
  src/styles/common/App.css
Labels: ✨ feature

#19 Feature/social-login 처리 후 응답으로부터 데이터 추출 로직 구현
  src.zip
  src/App.js
  src/components/Roll.js
  src/components/RollItem.js
  src/components/SocialLogin.js
  src/pages/LoginPage.js
  src/pages/MyPage.js
  src/pages/NaverRedirectHandler.js
Labels: ✨ feature, 🔗 api

#21 [Feature] 롤 수정 삭제 기능 구현
  public/images/logo/image_logo.png
  src/components/RollItem.js
  src/pages/MyPage.js
  src/pages/NaverRedirectHandler.js
Labels: ✨ feature, 🔗 api

#24 [Refactor] 소셜로그인 완료 후 백엔드와 연동하여 응답 처리 모듈로 리다이렉트
  src/App.js
  src/components/RollItem.js
  src/components/SocialLogin.js
  src/pages/KakaoRedirectHandler.js
  src/pages/LoginPage.js
  src/pages/MyPage.js
  src/pages/NaverRedirectHandler.js
  src/pages/RedirectHandler.js
Labels: 🔨 refactor, 🔗 api

#25 [Feature] Login 페이지 로고 이미지 변경 및 세부 CSS 수정
  package-lock.json
  package.json
  src/components/SocialLogin.js
  src/pages/LoginPage.js
  src/pages/StudentSigninPage.js
  src/styles/common/App.css
  src/styles/common/Logo.css
Labels: 🎨 markup, 🎯 ui/ux
